# Generated by Django 2.2.6 on 2019-10-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_one',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_two',
            field=models.CharField(max_length=200),
        ),
    ]
