# Generated by Django 2.2.6 on 2019-11-03 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20191014_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spanish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TextSpanish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_clip', models.TextField()),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Spanish')),
            ],
        ),
        migrations.CreateModel(
            name='ImageSpanish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=200)),
                ('image_description', models.CharField(max_length=250)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Spanish')),
            ],
        ),
    ]
